name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
- type: checkboxes
  id: first
  attributes:
    label: First
    description: you know stuff
    options:
      - label: Im human
        required: true
